version: '3'

services:
  scrapyd:
    image: vimagick/scrapyd
    ports:
      - "127.0.0.1:6800:6800"
    volumes:
      - ./data:/var/lib/scrapyd
    restart: unless-stopped

  scrapydweb:
    build:
      context: ./scrapyweb/
    depends_on:
      - scrapyd
    ports:
      - "6700:5000"
    environment:
      - SCRAPYD_SERVERS=scrapyd:6800
